{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app_name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app_name }}
  minReplicas: {{ .Values.hpa.minreplicas }}
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.updelay }}
      policies:
      - type: Percent
        value: 10
        periodSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.hpa.cpuutil }}
        type: Utilization  
{{- end }}
