# Generated by Django 5.0.6 on 2024-05-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_device',
            new_name='user_device_id',
        ),
    ]
