# Generated by Django 5.0.6 on 2024-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_user_device_notification_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='subs',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='token',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
