# Generated by Django 5.0.6 on 2024-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_user_device_id_notification_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
