# Generated by Django 5.0.6 on 2024-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0011_notification_notification_type_alter_category_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="bill_group",
            field=models.IntegerField(
                choices=[(0, "Индивидуальный"), (1, "Корпоративный")], default=0
            ),
            preserve_default=False,
        ),
    ]
