# Generated by Django 5.0.6 on 2024-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_notification_active_userdevice_bill_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="rtpl_id",
            field=models.IntegerField(null=True),
        ),
    ]
