# Generated by Django 5.0.6 on 2024-10-23 03:23

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_userdevice_rtpl_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="",
                        verbose_name="Картинка",
                    ),
                ),
                ("body", markdownx.models.MarkdownxField()),
                (
                    "button_title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название кнопки",
                    ),
                ),
                (
                    "button_route",
                    models.CharField(max_length=255, verbose_name="Ссылка на кнопке"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="detail",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.detailinfo",
            ),
        ),
    ]
