# Generated by Django 5.1.2 on 2024-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_detailinfo_body_alter_detailinfo_button_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
